ALTER TABLE bulk_csv_active_log RENAME TO csv_s3_archive_log;
ALTER INDEX idx_bulk_csv_active_log_checked_at RENAME TO idx_csv_s3_archive_log_checked_at;
ALTER INDEX idx_bulk_csv_active_log_sha256 RENAME TO idx_csv_s3_archive_log_sha256;

ALTER TABLE bulk_csv_archived_log RENAME TO archived_csv_s3_archive_log;
ALTER INDEX idx_bulk_csv_archived_log_fy_result RENAME TO idx_archived_csv_s3_archive_fy_result;
