-- Add name columns for place of performance state and country
ALTER TABLE opportunities ADD COLUMN pop_state_name TEXT;
ALTER TABLE opportunities ADD COLUMN pop_country_name TEXT;

-- Backfill state names from 2-letter codes
UPDATE opportunities SET
    pop_state_name = CASE UPPER(pop_state)
        WHEN 'AL' THEN 'Alabama'
        WHEN 'AK' THEN 'Alaska'
        WHEN 'AZ' THEN 'Arizona'
        WHEN 'AR' THEN 'Arkansas'
        WHEN 'CA' THEN 'California'
        WHEN 'CO' THEN 'Colorado'
        WHEN 'CT' THEN 'Connecticut'
        WHEN 'DE' THEN 'Delaware'
        WHEN 'FL' THEN 'Florida'
        WHEN 'GA' THEN 'Georgia'
        WHEN 'HI' THEN 'Hawaii'
        WHEN 'ID' THEN 'Idaho'
        WHEN 'IL' THEN 'Illinois'
        WHEN 'IN' THEN 'Indiana'
        WHEN 'IA' THEN 'Iowa'
        WHEN 'KS' THEN 'Kansas'
        WHEN 'KY' THEN 'Kentucky'
        WHEN 'LA' THEN 'Louisiana'
        WHEN 'ME' THEN 'Maine'
        WHEN 'MD' THEN 'Maryland'
        WHEN 'MA' THEN 'Massachusetts'
        WHEN 'MI' THEN 'Michigan'
        WHEN 'MN' THEN 'Minnesota'
        WHEN 'MS' THEN 'Mississippi'
        WHEN 'MO' THEN 'Missouri'
        WHEN 'MT' THEN 'Montana'
        WHEN 'NE' THEN 'Nebraska'
        WHEN 'NV' THEN 'Nevada'
        WHEN 'NH' THEN 'New Hampshire'
        WHEN 'NJ' THEN 'New Jersey'
        WHEN 'NM' THEN 'New Mexico'
        WHEN 'NY' THEN 'New York'
        WHEN 'NC' THEN 'North Carolina'
        WHEN 'ND' THEN 'North Dakota'
        WHEN 'OH' THEN 'Ohio'
        WHEN 'OK' THEN 'Oklahoma'
        WHEN 'OR' THEN 'Oregon'
        WHEN 'PA' THEN 'Pennsylvania'
        WHEN 'RI' THEN 'Rhode Island'
        WHEN 'SC' THEN 'South Carolina'
        WHEN 'SD' THEN 'South Dakota'
        WHEN 'TN' THEN 'Tennessee'
        WHEN 'TX' THEN 'Texas'
        WHEN 'UT' THEN 'Utah'
        WHEN 'VT' THEN 'Vermont'
        WHEN 'VA' THEN 'Virginia'
        WHEN 'WA' THEN 'Washington'
        WHEN 'WV' THEN 'West Virginia'
        WHEN 'WI' THEN 'Wisconsin'
        WHEN 'WY' THEN 'Wyoming'
        WHEN 'DC' THEN 'District of Columbia'
        WHEN 'PR' THEN 'Puerto Rico'
        WHEN 'GU' THEN 'Guam'
        WHEN 'VI' THEN 'U.S. Virgin Islands'
        WHEN 'AS' THEN 'American Samoa'
        WHEN 'MP' THEN 'Northern Mariana Islands'
        ELSE pop_state
    END,
    pop_country_name = CASE UPPER(pop_country)
        WHEN 'AFG' THEN 'Afghanistan'
        WHEN 'ALB' THEN 'Albania'
        WHEN 'DZA' THEN 'Algeria'
        WHEN 'ASM' THEN 'American Samoa'
        WHEN 'AND' THEN 'Andorra'
        WHEN 'AGO' THEN 'Angola'
        WHEN 'AIA' THEN 'Anguilla'
        WHEN 'ATA' THEN 'Antarctica'
        WHEN 'ATG' THEN 'Antigua and Barbuda'
        WHEN 'ARG' THEN 'Argentina'
        WHEN 'ARM' THEN 'Armenia'
        WHEN 'ABW' THEN 'Aruba'
        WHEN 'AUS' THEN 'Australia'
        WHEN 'AUT' THEN 'Austria'
        WHEN 'AZE' THEN 'Azerbaijan'
        WHEN 'BHS' THEN 'Bahamas'
        WHEN 'BHR' THEN 'Bahrain'
        WHEN 'BGD' THEN 'Bangladesh'
        WHEN 'BRB' THEN 'Barbados'
        WHEN 'BLR' THEN 'Belarus'
        WHEN 'BEL' THEN 'Belgium'
        WHEN 'BLZ' THEN 'Belize'
        WHEN 'BEN' THEN 'Benin'
        WHEN 'BMU' THEN 'Bermuda'
        WHEN 'BTN' THEN 'Bhutan'
        WHEN 'BOL' THEN 'Bolivia'
        WHEN 'BES' THEN 'Bonaire, Sint Eustatius and Saba'
        WHEN 'BIH' THEN 'Bosnia and Herzegovina'
        WHEN 'BWA' THEN 'Botswana'
        WHEN 'BVT' THEN 'Bouvet Island'
        WHEN 'BRA' THEN 'Brazil'
        WHEN 'IOT' THEN 'British Indian Ocean Territory'
        WHEN 'BRN' THEN 'Brunei'
        WHEN 'BGR' THEN 'Bulgaria'
        WHEN 'BFA' THEN 'Burkina Faso'
        WHEN 'BDI' THEN 'Burundi'
        WHEN 'CPV' THEN 'Cabo Verde'
        WHEN 'KHM' THEN 'Cambodia'
        WHEN 'CMR' THEN 'Cameroon'
        WHEN 'CAN' THEN 'Canada'
        WHEN 'CYM' THEN 'Cayman Islands'
        WHEN 'CAF' THEN 'Central African Republic'
        WHEN 'TCD' THEN 'Chad'
        WHEN 'CHL' THEN 'Chile'
        WHEN 'CHN' THEN 'China'
        WHEN 'CXR' THEN 'Christmas Island'
        WHEN 'CCK' THEN 'Cocos (Keeling) Islands'
        WHEN 'COL' THEN 'Colombia'
        WHEN 'COM' THEN 'Comoros'
        WHEN 'COG' THEN 'Congo'
        WHEN 'COD' THEN 'Democratic Republic of the Congo'
        WHEN 'COK' THEN 'Cook Islands'
        WHEN 'CRI' THEN 'Costa Rica'
        WHEN 'CIV' THEN 'Ivory Coast'
        WHEN 'HRV' THEN 'Croatia'
        WHEN 'CUB' THEN 'Cuba'
        WHEN 'CUW' THEN 'Curacao'
        WHEN 'CYP' THEN 'Cyprus'
        WHEN 'CZE' THEN 'Czechia'
        WHEN 'DNK' THEN 'Denmark'
        WHEN 'DJI' THEN 'Djibouti'
        WHEN 'DMA' THEN 'Dominica'
        WHEN 'DOM' THEN 'Dominican Republic'
        WHEN 'ECU' THEN 'Ecuador'
        WHEN 'EGY' THEN 'Egypt'
        WHEN 'SLV' THEN 'El Salvador'
        WHEN 'GNQ' THEN 'Equatorial Guinea'
        WHEN 'ERI' THEN 'Eritrea'
        WHEN 'EST' THEN 'Estonia'
        WHEN 'SWZ' THEN 'Eswatini'
        WHEN 'ETH' THEN 'Ethiopia'
        WHEN 'FLK' THEN 'Falkland Islands'
        WHEN 'FRO' THEN 'Faroe Islands'
        WHEN 'FJI' THEN 'Fiji'
        WHEN 'FIN' THEN 'Finland'
        WHEN 'FRA' THEN 'France'
        WHEN 'GUF' THEN 'French Guiana'
        WHEN 'PYF' THEN 'French Polynesia'
        WHEN 'ATF' THEN 'French Southern Territories'
        WHEN 'GAB' THEN 'Gabon'
        WHEN 'GMB' THEN 'Gambia'
        WHEN 'GEO' THEN 'Georgia'
        WHEN 'DEU' THEN 'Germany'
        WHEN 'GHA' THEN 'Ghana'
        WHEN 'GIB' THEN 'Gibraltar'
        WHEN 'GRC' THEN 'Greece'
        WHEN 'GRL' THEN 'Greenland'
        WHEN 'GRD' THEN 'Grenada'
        WHEN 'GLP' THEN 'Guadeloupe'
        WHEN 'GUM' THEN 'Guam'
        WHEN 'GTM' THEN 'Guatemala'
        WHEN 'GGY' THEN 'Guernsey'
        WHEN 'GIN' THEN 'Guinea'
        WHEN 'GNB' THEN 'Guinea-Bissau'
        WHEN 'GUY' THEN 'Guyana'
        WHEN 'HTI' THEN 'Haiti'
        WHEN 'HMD' THEN 'Heard Island and McDonald Islands'
        WHEN 'VAT' THEN 'Vatican City'
        WHEN 'HND' THEN 'Honduras'
        WHEN 'HKG' THEN 'Hong Kong'
        WHEN 'HUN' THEN 'Hungary'
        WHEN 'ISL' THEN 'Iceland'
        WHEN 'IND' THEN 'India'
        WHEN 'IDN' THEN 'Indonesia'
        WHEN 'IRN' THEN 'Iran'
        WHEN 'IRQ' THEN 'Iraq'
        WHEN 'IRL' THEN 'Ireland'
        WHEN 'IMN' THEN 'Isle of Man'
        WHEN 'ISR' THEN 'Israel'
        WHEN 'ITA' THEN 'Italy'
        WHEN 'JAM' THEN 'Jamaica'
        WHEN 'JPN' THEN 'Japan'
        WHEN 'JEY' THEN 'Jersey'
        WHEN 'JOR' THEN 'Jordan'
        WHEN 'KAZ' THEN 'Kazakhstan'
        WHEN 'KEN' THEN 'Kenya'
        WHEN 'KIR' THEN 'Kiribati'
        WHEN 'PRK' THEN 'North Korea'
        WHEN 'KOR' THEN 'South Korea'
        WHEN 'KWT' THEN 'Kuwait'
        WHEN 'KGZ' THEN 'Kyrgyzstan'
        WHEN 'LAO' THEN 'Laos'
        WHEN 'LVA' THEN 'Latvia'
        WHEN 'LBN' THEN 'Lebanon'
        WHEN 'LSO' THEN 'Lesotho'
        WHEN 'LBR' THEN 'Liberia'
        WHEN 'LBY' THEN 'Libya'
        WHEN 'LIE' THEN 'Liechtenstein'
        WHEN 'LTU' THEN 'Lithuania'
        WHEN 'LUX' THEN 'Luxembourg'
        WHEN 'MAC' THEN 'Macao'
        WHEN 'MDG' THEN 'Madagascar'
        WHEN 'MWI' THEN 'Malawi'
        WHEN 'MYS' THEN 'Malaysia'
        WHEN 'MDV' THEN 'Maldives'
        WHEN 'MLI' THEN 'Mali'
        WHEN 'MLT' THEN 'Malta'
        WHEN 'MHL' THEN 'Marshall Islands'
        WHEN 'MTQ' THEN 'Martinique'
        WHEN 'MRT' THEN 'Mauritania'
        WHEN 'MUS' THEN 'Mauritius'
        WHEN 'MYT' THEN 'Mayotte'
        WHEN 'MEX' THEN 'Mexico'
        WHEN 'FSM' THEN 'Micronesia'
        WHEN 'MDA' THEN 'Moldova'
        WHEN 'MCO' THEN 'Monaco'
        WHEN 'MNG' THEN 'Mongolia'
        WHEN 'MNE' THEN 'Montenegro'
        WHEN 'MSR' THEN 'Montserrat'
        WHEN 'MAR' THEN 'Morocco'
        WHEN 'MOZ' THEN 'Mozambique'
        WHEN 'MMR' THEN 'Myanmar'
        WHEN 'NAM' THEN 'Namibia'
        WHEN 'NRU' THEN 'Nauru'
        WHEN 'NPL' THEN 'Nepal'
        WHEN 'NLD' THEN 'Netherlands'
        WHEN 'NCL' THEN 'New Caledonia'
        WHEN 'NZL' THEN 'New Zealand'
        WHEN 'NIC' THEN 'Nicaragua'
        WHEN 'NER' THEN 'Niger'
        WHEN 'NGA' THEN 'Nigeria'
        WHEN 'NIU' THEN 'Niue'
        WHEN 'NFK' THEN 'Norfolk Island'
        WHEN 'MKD' THEN 'North Macedonia'
        WHEN 'MNP' THEN 'Northern Mariana Islands'
        WHEN 'NOR' THEN 'Norway'
        WHEN 'OMN' THEN 'Oman'
        WHEN 'PAK' THEN 'Pakistan'
        WHEN 'PLW' THEN 'Palau'
        WHEN 'PSE' THEN 'Palestine'
        WHEN 'PAN' THEN 'Panama'
        WHEN 'PNG' THEN 'Papua New Guinea'
        WHEN 'PRY' THEN 'Paraguay'
        WHEN 'PER' THEN 'Peru'
        WHEN 'PHL' THEN 'Philippines'
        WHEN 'PCN' THEN 'Pitcairn'
        WHEN 'POL' THEN 'Poland'
        WHEN 'PRT' THEN 'Portugal'
        WHEN 'PRI' THEN 'Puerto Rico'
        WHEN 'QAT' THEN 'Qatar'
        WHEN 'REU' THEN 'Reunion'
        WHEN 'ROU' THEN 'Romania'
        WHEN 'RUS' THEN 'Russia'
        WHEN 'RWA' THEN 'Rwanda'
        WHEN 'BLM' THEN 'Saint Barthelemy'
        WHEN 'SHN' THEN 'Saint Helena'
        WHEN 'KNA' THEN 'Saint Kitts and Nevis'
        WHEN 'LCA' THEN 'Saint Lucia'
        WHEN 'MAF' THEN 'Saint Martin'
        WHEN 'SPM' THEN 'Saint Pierre and Miquelon'
        WHEN 'VCT' THEN 'Saint Vincent and the Grenadines'
        WHEN 'WSM' THEN 'Samoa'
        WHEN 'SMR' THEN 'San Marino'
        WHEN 'STP' THEN 'Sao Tome and Principe'
        WHEN 'SAU' THEN 'Saudi Arabia'
        WHEN 'SEN' THEN 'Senegal'
        WHEN 'SRB' THEN 'Serbia'
        WHEN 'SYC' THEN 'Seychelles'
        WHEN 'SLE' THEN 'Sierra Leone'
        WHEN 'SGP' THEN 'Singapore'
        WHEN 'SXM' THEN 'Sint Maarten'
        WHEN 'SVK' THEN 'Slovakia'
        WHEN 'SVN' THEN 'Slovenia'
        WHEN 'SLB' THEN 'Solomon Islands'
        WHEN 'SOM' THEN 'Somalia'
        WHEN 'ZAF' THEN 'South Africa'
        WHEN 'SGS' THEN 'South Georgia and the South Sandwich Islands'
        WHEN 'SSD' THEN 'South Sudan'
        WHEN 'ESP' THEN 'Spain'
        WHEN 'LKA' THEN 'Sri Lanka'
        WHEN 'SDN' THEN 'Sudan'
        WHEN 'SUR' THEN 'Suriname'
        WHEN 'SJM' THEN 'Svalbard and Jan Mayen'
        WHEN 'SWE' THEN 'Sweden'
        WHEN 'CHE' THEN 'Switzerland'
        WHEN 'SYR' THEN 'Syria'
        WHEN 'TWN' THEN 'Taiwan'
        WHEN 'TJK' THEN 'Tajikistan'
        WHEN 'TZA' THEN 'Tanzania'
        WHEN 'THA' THEN 'Thailand'
        WHEN 'TLS' THEN 'Timor-Leste'
        WHEN 'TGO' THEN 'Togo'
        WHEN 'TKL' THEN 'Tokelau'
        WHEN 'TON' THEN 'Tonga'
        WHEN 'TTO' THEN 'Trinidad and Tobago'
        WHEN 'TUN' THEN 'Tunisia'
        WHEN 'TUR' THEN 'Turkey'
        WHEN 'TKM' THEN 'Turkmenistan'
        WHEN 'TCA' THEN 'Turks and Caicos Islands'
        WHEN 'TUV' THEN 'Tuvalu'
        WHEN 'UGA' THEN 'Uganda'
        WHEN 'UKR' THEN 'Ukraine'
        WHEN 'ARE' THEN 'United Arab Emirates'
        WHEN 'GBR' THEN 'United Kingdom'
        WHEN 'USA' THEN 'United States'
        WHEN 'UMI' THEN 'United States Minor Outlying Islands'
        WHEN 'URY' THEN 'Uruguay'
        WHEN 'UZB' THEN 'Uzbekistan'
        WHEN 'VUT' THEN 'Vanuatu'
        WHEN 'VEN' THEN 'Venezuela'
        WHEN 'VNM' THEN 'Vietnam'
        WHEN 'VGB' THEN 'British Virgin Islands'
        WHEN 'VIR' THEN 'U.S. Virgin Islands'
        WHEN 'WLF' THEN 'Wallis and Futuna'
        WHEN 'ESH' THEN 'Western Sahara'
        WHEN 'YEM' THEN 'Yemen'
        WHEN 'ZMB' THEN 'Zambia'
        WHEN 'ZWE' THEN 'Zimbabwe'
        WHEN 'ALA' THEN 'Aland Islands'
        ELSE pop_country
    END
WHERE pop_state IS NOT NULL OR pop_country IS NOT NULL;

-- Update search vector trigger to include place of performance name columns
CREATE OR REPLACE FUNCTION update_opportunities_search_vector()
RETURNS TRIGGER AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', COALESCE(NEW.solicitation_number, '')), 'A') ||
        setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'B') ||
        setweight(to_tsvector('english', COALESCE(NEW.department, '')), 'C') ||
        setweight(to_tsvector('english', COALESCE(NEW.sub_tier, '')), 'C') ||
        setweight(to_tsvector('english', COALESCE(NEW.office, '')), 'C') ||
        setweight(to_tsvector('english', COALESCE(NEW.notice_id, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.set_aside_description, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.awardee_name, NEW.awardee, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.classification_code, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.naics_code, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.pop_city, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.pop_state_name, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.pop_country_name, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.award_number, '')), 'D') ||
        setweight(to_tsvector('english', COALESCE(NEW.primary_contact_fullname, '')), 'D');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rebuild search vectors for all existing rows
UPDATE opportunities SET search_vector = search_vector;
