-- Remove all remaining varchar length constraints on opportunities table.
-- PostgreSQL has no performance difference between text and varchar(n),
-- and SAM.gov data is messy (e.g. phone fields containing email instructions).
-- Tight limits cause cascading batch failures in pgx pipeline mode.

ALTER TABLE opportunities
    ALTER COLUMN solicitation_number TYPE text,
    ALTER COLUMN type TYPE text,
    ALTER COLUMN base_type TYPE text,
    ALTER COLUMN organization_type TYPE text,
    ALTER COLUMN archive_type TYPE text,
    ALTER COLUMN set_aside_code TYPE text,
    ALTER COLUMN naics_code TYPE text,
    ALTER COLUMN classification_code TYPE text,
    ALTER COLUMN pop_city_code TYPE text,
    ALTER COLUMN pop_city_name TYPE text,
    ALTER COLUMN pop_state_code TYPE text,
    ALTER COLUMN pop_state_name TYPE text,
    ALTER COLUMN pop_country_code TYPE text,
    ALTER COLUMN pop_country_name TYPE text,
    ALTER COLUMN pop_zip TYPE text,
    ALTER COLUMN office_city TYPE text,
    ALTER COLUMN office_state TYPE text,
    ALTER COLUMN office_zip TYPE text,
    ALTER COLUMN office_country_code TYPE text,
    ALTER COLUMN award_number TYPE text,
    ALTER COLUMN awardee_uei TYPE text,
    ALTER COLUMN awardee_city TYPE text,
    ALTER COLUMN awardee_state TYPE text,
    ALTER COLUMN awardee_country TYPE text,
    ALTER COLUMN awardee_zip TYPE text,
    ALTER COLUMN cgac TYPE text,
    ALTER COLUMN fpds_code TYPE text,
    ALTER COLUMN aac_code TYPE text,
    ALTER COLUMN primary_contact_title TYPE text,
    ALTER COLUMN primary_contact_phone TYPE text,
    ALTER COLUMN primary_contact_fax TYPE text,
    ALTER COLUMN secondary_contact_title TYPE text,
    ALTER COLUMN secondary_contact_phone TYPE text,
    ALTER COLUMN secondary_contact_fax TYPE text,
    ALTER COLUMN data_source TYPE text,
    ALTER COLUMN notice_id TYPE text;
